drupal_major_version: 7

drupal_build_makefile: true
drupal_build_composer_project: false

drupal_enable_modules: []

# The web server software to use. Can be either 'apache' or 'nginx'.
drupalvm_webserver: nginx

# The database system to use. Can be either 'mysql' or 'pgsql'.
drupal_db_backend: pgsql

installed_extras:
  - adminer
  - drush
  - mailhog
  - pimpmylog
  - upload-progress
  - xdebug

drush_launcher_install: no
drush_install_from_source: yes
drush_source_install_version: "8.1.15"
